# Generated by Django 5.1.3 on 2026-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=80),
            preserve_default=False,
        ),
    ]
